### ISSUE TITLE
Manuscript improvement

### ISSUE THREAD

**Issue by SunnyXu** [markur4/plotastic#1]
Please pay attention to some points in the manuscript.
(1) There is not supposed to be a period mark before the citation on line 26, and the citation on line 37 with the front bracket placed at a wrong position.
(2) Figure 1 is not cited in the content of the manuscript.

**Comment by markur4** [comment]
Thank you for pointing out these points! I have made these edits:
(1)
  -  Former line 26: The period before (Waskom, 2021) has been removed.
  -  Former line 37: The citations have been corrected. 
(2) Fig. 1 has been referenced after the first sentence of the 'example section'

**Comment by SunnyXu** [comment]
Hi, I have just noticed that there is another period mark before the citation on line 26.
