### ISSUE TITLE
Some parts of the Documentation are empty

### ISSUE THREAD

**Issue by SunnyXu** [markur4/plotastic#4]
Please either remove or complete them.
1 Example Gallery– i Quick Example: FMRI: it shows 404
https://github.com/markur4/plotastic/blob/main/HOW_TO_USE/quick_example_fmri.ipynb
2 Data- i Transform Y: no link
3 Plotting- iii Editing Figures: no content

**Comment by markur4** [comment]
I appreciate the detailed review! I made these corrections:
(1) Corrected the link to fmri
(2) Removed Transform Y (will be added later)
(3) Removed Editing Figures (will be added later)
